services:
  marinus-dev-backend:
    build: .
    ports:
      - "${EXPOSED_MARINUS_DEV_API_PORT}:8080"
    volumes:
      - .:/code
      - marinus-dev-backend:/var/log
    depends_on:
      - mariadb
    env_file:
      - .env
    deploy:
      resources:
        limits:
          cpus: '2'
          memory: 300M
        reservations:
          cpus: '1.50'
          memory: 100M
  mariadb:
    image: mariadb
    ports:
      - "3306:3306"
    environment:
      MYSQL_DATABASE: marinus-dev-backend
      MYSQL_USER: admin
      MYSQL_PASSWORD: adminpw
      MYSQL_ROOT_PASSWORD: rootpw
    deploy:
      resources:
        limits:
          cpus: '0.10'
          memory: 200M
        reservations:
          cpus: '0.10'
          memory: 50M
volumes:
  marinus-dev-backend: { }
